image:
  file: .gitpod.Dockerfile

tasks:
  - name: إعداد Flutter
    init: |
      export PATH="/home/gitpod/flutter/bin:$PATH"
      flutter doctor

vscode:
  extensions:
    - Dart-Code.flutter
    - Dart-Code.dart-code

ports:
  - port: 3000
    onOpen: open-preview
